@BASE_URL = http://localhost:8899

#Login
POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
    "identity": "andy@ggg.mail",
    "password": "123456" 
}


###
#Get me
GET {{BASE_URL}}/api/auth/me


###
#Register
POST {{BASE_URL}}/api/auth/register
Content-Type: application/json

{
    #  "identity" : "andy",
     "identity" : "11111111112",
# "identity" : "andeez@ggg.mail",
"firstName" : "someone", "lastName" : "codecamp", "password" : "123456", "confirmPassword" : "123456"
}


###
#Post message
POST {{BASE_URL}}/api/post
Content-Type: application/json


###
#notfound test
GET {{BASE_URL}}/api/products